[colors.primary]
background = "#000000"
foreground = "#e0e0e0"

[colors.normal]
black = "#000000"
red = "#cc0403"
green = "#19cb00"
yellow = "#cecb00"
blue = "#0d73cc"
magenta = "#cb1ed1"
cyan = "#0dcdcd"
white = "#e0e0e0"

[colors.bright]
black = "#767676"
red = "#ff8800"
green = "#19cb00"
yellow = "#cecb00"
blue = "#0d73cc"
magenta = "#cb1ed1"
cyan = "#0dcdcd"
white = "#ffffff"

[colors.selection]
background = "#505050"
text = "#e0e0e0"
