palette = 0=#000000
palette = 1=#cc0403
palette = 2=#19cb00
palette = 3=#cecb00
palette = 4=#0d73cc
palette = 5=#cb1ed1
palette = 6=#0dcdcd
palette = 7=#e0e0e0
palette = 8=#767676
palette = 9=#ff8800
palette = 10=#19cb00
palette = 11=#cecb00
palette = 12=#0d73cc
palette = 13=#cb1ed1
palette = 14=#0dcdcd
palette = 15=#ffffff

background = #000000
foreground = #e0e0e0
cursor-color = #e0e0e0
cursor-text = #000000
selection-background = #505050
selection-foreground = #e0e0e0
