## name: Glats
## license: MIT
## author: glats

background #000000
foreground #e0e0e0
selection_background #505050
selection_foreground #e0e0e0
url_color #0dcdcd
cursor #e0e0e0
cursor_text_color #000000

# Tabs
active_tab_background #0d73cc
active_tab_foreground #000000
inactive_tab_background #0a0a0a
inactive_tab_foreground #767676

# Windows
active_border_color #0d73cc
inactive_border_color #0a0a0a

# normal
color0 #000000
color1 #cc0403
color2 #19cb00
color3 #cecb00
color4 #0d73cc
color5 #cb1ed1
color6 #0dcdcd
color7 #e0e0e0

# bright
color8 #767676
color9 #ff8800
color10 #19cb00
color11 #cecb00
color12 #0d73cc
color13 #cb1ed1
color14 #0dcdcd
color15 #ffffff

# extended colors
color16 #ff6600
color17 #cc0403
